### ISSUE TITLE
Mismatched version of winit dependency prevents example compilation

### ISSUE THREAD

**Issue by lucas-riedlshah** [zlosynth/gazpatcho#38]
I am getting this error in my editor on the use statements at the top. The code I am attempting to run is the same as that which you have in the "main" example. 

When I attempt to run the code I get 5 errors similar to the following, which all claim the same type error (E0308) and all with winit and glium::glutin clashing.

Here is one of the errors I get:
```
error[E0308]: mismatched types
   --> C:\Users\UserFolder\.cargo\registry\src\github.com-1ecc6299db9ec823\gazpatcho-1.4.1\src\engine\system.rs:120:75
    |
120 |                 platform.handle_event(imgui.io_mut(), gl_window.window(), &event);
    |                                                                           ^^^^^^ expected enum `winit::event::Event`, found enum 
`Event`
    |
    = note: expected reference `&winit::event::Event<'_, _>`
               found reference `&Event<'_, ()>`
    = note: perhaps two different versions of crate `winit` are being used?
```

I'm new to rust and really cannot seem to figure this one out. 

Cheers :)

**Comment by phoracek** [comment]
Thanks for reporting this Issue @generatively. Ouch, I believed I solved this with https://github.com/zlosynth/gazpatcho/commit/55cfa7e93064f42f0eb449243abdb8168ef4faaf, but seems that it is still around. Let me try to debug this, I bet we have to pin some other dependency.

**Comment by phoracek** [comment]
I'm bumping imgui-rs to version 0.7. They mention a similar issue in their [changelog](https://github.com/imgui-rs/imgui-rs/blob/b3f55585570edcb3858b8f6e25ca151828c4d423/CHANGELOG.markdown#070---2021-02-04).

@generatively could you please pull the latest commit from `main` branch to see if it now compiles for you? If it will work all right, I would release a new version.

**Comment by lucas-riedlshah** [comment]
Compiles without a problem now 👍
