### ISSUE TITLE
White screen on main example (X11)

### ISSUE THREAD

**Issue by Sinono3** [zlosynth/gazpatcho#40]
When running the main example, the window is just white. Resizing does nothing. I'm on Void Linux using X11 with bspwm. I can provide more info.

![image](https://user-images.githubusercontent.com/8389938/132266553-fb38f210-3e3f-495f-b467-588943b9cd37.png)

**Comment by phoracek** [comment]
Hello @Sinono3, thanks for reporting this. What you see is intentional, you can access the menu by right-clicking anywhere on the blank screen, from there you can add nodes. Please let me know if that helped.

**Comment by Sinono3** [comment]
It works now, thank you. The controls should probably be shown somewhere, since it wasn't clear that was the desired behaviour. Maybe they were in the docs, but I couldn't find them :crying_cat_face:

**Comment by phoracek** [comment]
You are right. Maybe we should add a little message to the middle of the empty screen hinting to right-click. And remove this message once there is anything added.
